### ISSUE TITLE
Job and Queue Configuration

### ISSUE THREAD

**Issue by mperham** [rails/activejob#47]
Figured I'd open up an issue to discuss this since it's pretty important to tweak various options that the underlying job systems provide.  What should go where?

A very simple initial proposal:

``` ruby
class SomeJob < ActiveJob::Base
  job_options retry: false

  def perform(args)
  end
end
```

The options hash can then be accessed by the adapter along with the arguments.

**Comment by chinshr** [comment]
I also wanted to know how to realize `job_options retry: false` with ActiveJob standard features. Currently, failed jobs get re-queued, which is annoying.

**Comment by guizmaii** [comment]
I have the same question as @chinshr. 
I'm using ActiveJob with Sidekiq. Is there a way to disable automatic retry ?

**Comment by seuros** [comment]
Yes, use a Sidekiq class.

**Comment by dhh** [comment]
Or add a rescue_from that doesn't re raise ore reque.

**Comment by axsuul** [comment]
Would love to see some sort of interface that allows us to pass in adapter specific options. Otherwise isn't `ActiveJob` not powerful enough?

**Comment by jacquescrocker** [comment]
Does anyone have a solution here? Using ActiveJob now means I can't configure custom Sidekiq settings for my worker (like retry and other extensions).

**Comment by chinshr** [comment]
It's pretty straightforward using a rescue and not throwing the exception, worked for me.

**Comment by IlkhamGaysin** [comment]
@jacquescrocker yeah as @chinshr said you can catch up the exception by rescue_from

``` ruby
  class ExampleJob < ActiveJob::Base
    rescue_from(StandardError) do |exception|
      Rails.logger.error "[#{self.class.name}] Hey, something was wrong with you job #{exception.to_s}"       
    end

    def perform
      raise StandardError, "error_message"
    end
  end

  class ExampleJob < ActiveJob::Base
    rescue_from(StandardError) do |exception|
      retry_job wait: 5.minutes, queue: :low_priority     
    end

    def perform
      raise StandardError, "error_message"
    end
  end

```

For running retrying you can use retry_on method 
[Active Job doc for retry_on](https://github.com/rails/rails/blob/fe1f4b2ad56f010a4e9b93d547d63a15953d9dc2/activejob/lib/active_job/exceptions.rb#L26)

[Sidekiq wiki for retries with Active Job integration](https://github.com/mperham/sidekiq/wiki/Active-Job#customizing-error-handling)

**Comment by ivanovaleksey** [comment]
And what about using ActiveJob in mailers?
Given mailer with nonexistent email would result in numerous useless retries.
I don't have explicit ActiveJob class to configure anything.
Is there any solution for it?
