### ISSUE TITLE
Add a proper usage guide

### ISSUE THREAD

**Issue by dhh** [rails/activejob#66]
Let's get a Rails Guide started for ActiveJob. Something ala http://guides.rubyonrails.org/active_record_basics.html. Explain why you would want to delay work in jobs, how to do it, etc.

**Comment by jwworth** [comment]
Could this issue be closed, via: http://guides.rubyonrails.org/active_job_basics.html ?

**Comment by seuros** [comment]
@jwworth this repo is not used anymore. Active job was merged into rails.
