### ISSUE TITLE
[Feature request] Cancel jobs

### ISSUE THREAD

**Issue by seuros** [rails/activejob#70]
@rafaelfranca , @cristianbica , @dhh 
Should we add API to cancel jobs that were enqueue and not performed yet ?

**Comment by sekrett** [comment]
I have an example where it would be needed a cancel API or reschedule API. We have a mailing list, suppose we have planned a mail delivery for tomorrow and later we decide to send it at a different time or not to send it at all. It's easy to handle a "record not found" error if we want to cancel but if we change delivery time, it is a bit complicated.

**Comment by zw963** [comment]
Another example:
A order system, when some guy make a order, will create a delayed job, to automatic close this order
if in 3 days not pay for money, But, if this guy pay for this, we hope can cancel this delayed job.

**Comment by seuros** [comment]
Just NOP if the order is already paid.

**Comment by zw963** [comment]
I use Sidekiq, Sidekiq support cancel API to do this, But, It hard to get JobId for this.

Because ActiveJob return a difference job_id with sidekiq, it can not used directly in Sidekiq.

**Comment by zw963** [comment]
@seuros , Oh, Thanks.

**Comment by seuros** [comment]
Sidekiq don't support job cancellation IFAIK.

**Comment by zw963** [comment]
@seuros , Thank, What I say is cancel a job in a Queue.

```sh
Deletes jobs within the queue mailer with a jid of 'abcdef1234567890'

queue = Sidekiq::Queue.new("mailer")
queue.each do |job|
  job.klass # => 'MyWorker'
  job.args # => [1, 2, 3]
  job.delete if job.jid == 'abcdef1234567890'
end
```

It seem like not same as job cancellation ?

**Comment by zw963** [comment]
@seuros , Could you give me a replay for sidekiq job cancellation? 

I don't know what your means. `Sidekiq don't support job cancellation`

Thanks.

**Comment by michaelimstepf** [comment]
Here's our use case:

We send out text messages for appointment reminders. Sometimes appointments get cancelled, in which case we don't want a reminder (job) to be sent out. We would also like to delete and re-create a reminder (job) when the appointment time changes.

Details: http://stackoverflow.com/questions/29814262/active-job-delete-existing-job

**Comment by smikkelsen** [comment]
I don't understand the pushback? It seems like most queues support this. I've been doing it for years in Delayed Job. This is a pretty necessary feature I think.

I personally don't like the idea of just creating a new job every time a change is made and expect the old jobs to re-evaluate whether they are supposed to do anything at runtime.

**Comment by michaelimstepf** [comment]
Regarding the use case I presented above, we solved it by creating a daily task that queries all appointments for the next day and sends out appointment reminders at present time so there's no longer a need for us to delete jobs.

**Comment by davidlumley** [comment]
A really common use case I've ran into, is being able to undo actions. In most cases: sending email.

- A user clicks send.
- The application enqueues the email for sending in 30 seconds (an arbitrary "short amount of time" period) and the user is presented an 'Your email is sending. Click here to undo' flash message.
- A user clicks undo/cancel, and the job is cancelled before running, and therefore the email is not sent.

**Comment by mperham** [comment]
@davidlumley This is easy to implement with Sidekiq. https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job

**Comment by davidlumley** [comment]
@mperham – that's how I've been doing it currently :)

**Comment by wfried** [comment]
I also would like to be able to cancel jobs.  My scenario is that I send out a reminder email as a (real-world) event approaches.  That event may be rescheduled, in which case the reminder needs to be rescheduled.  Yes, it's possible to add jobs every time the event is rescheduled, and make each job check the event to see if the time is still correct, and I do this now.  But it would be cleaner, in my view, to allow me to cancel the out-of-date jobs when I schedule the new jobs.

From the discussion here it sounds like the major underlying engines support this functionality.  It would be helpful for Rails to support it as well in ActiveJob.

**Comment by dhh** [comment]
I'd be happy to see a uniform interface for canceling jobs. Not so
interested in exposing each underlying engine's method, though. Should be a
uniform interface.

**Comment by wfried** [comment]
That would be great!!

**Comment by dimanlin** [comment]
+1

**Comment by wfried** [comment]
Is this being looked at actively? I'm getting some pressure to go back to using DelayedJobs directly since it supports cancelling jobs as we now have another scenario where we need this.

**Comment by dhh** [comment]
I don't know of anyone actively working on this, but I'd support adding
this to AJ. So if you want to take a swing at a solution, please do dig in.

**Comment by jeremyk** [comment]
It can be hard to know at runtime if a job should be processed. Say you let the user decide when to get a reminder email. And they toggle back and forth 4 times from 30 to 60 minutes and end up leaving it on 30. We have now created a bunch of jobs to send that reminder email and the 60 minute ones will be easily invalidated at run time but how do we know which one of the 30 minute ones we want to run? I can think of solutions but nothing as simple as being able to cancel the existing jobs. Am I missing something?

**Comment by dhh** [comment]
Jeremy, I think cancelation is a fine way to go. Another is to validate
when the job is run that it's still the valid job to run. You can have a
redis state check or whatever. But +1 to allowing cancelations.

**Comment by mperham** [comment]
An alternate take: http://lanceolsen.net/never-schedule-future-jobs/

I wouldn't say "never", but user-reschedulable jobs probably shouldn't be enqueued in advance.

**Comment by cristianbica** [comment]
@jeremyk if you're using delayed job AJ will return the `Delayed::Job` instance when you schedule a job. You can use that to remember the job ID and destroy the `Delayed::Job` record when you want to cancel.

**Comment by ConfusedVorlon** [comment]
deleting jobs is nice in testing. 

```
do_some_setup_that_enqueues_jobs
delete_jobs

do_thing_that_should_trigger_job

assert_enqueued_jobs 1
```

I can use a change assertion to work round this - but I prefer deleting
