### ISSUE TITLE
Should we add a delayed mixin so users can delay any method? 

### ISSUE THREAD

**Issue by cristianbica** [rails/activejob#88]
One common feature when using background tasks is to have the ability to `delay` any method from any class/instance in your app. There two variants:

1 - Declare the method as "delayed" (aka delayed_job's handle_asynchronously):

``` ruby
class SomeClasses
  def self.a_method(*)
  end
  delay :a_method
end
```

So if you do `SomeClasses.a_method(1,2,3)` it will actually schedule a job. Here's an implementation I used on a project https://gist.github.com/cristianbica/7706419.

2 - Have a `delay` method for each object which will schedule anything after it:

``` ruby
class SomeClass
  include ActiveJob::Delayable
  def self.method1(*)
  end

  def method2(*)
  end
end

SomeClass.delay.method1(1,2,3)
SomeClass.delay(queue: :lowprio).method1(1,2,3)
SomeClass.delay_until(5.minutes.from_now, queue: :lowprio).method1(1,2,3)
SomeClass.new.delay.method2(1,2,3)
```

Which variant do you prefer? Should we add this feature in AJ or as a gem?

@mperham what do you think? I "suspect" that you rejected this kind of stuff from core sidekiq, right?

/cc @dhh, @seuros, @DouweM, @rafaelfranca 

PS: I'm for variant 2 and not sure if in AJ or gem (I'm slightly inclined to a gem and if we see massive adoption we can merge it inside AJ/rails)

**Comment by swrobel** [comment]
Did activejob-delay ever come to be? The only thing I could find is https://github.com/alpaca-tc/activejob-delayed_execution which seems unrelated.

**Comment by Carpela** [comment]
I think this is where it ended up, in case it helps anyone. 
https://github.com/cristianbica/activejob-perform_later
